### ISSUE TITLE
Running QGIS flatpak throws No module named 'PyQt5.QtWebKit'

### ISSUE THREAD

**Issue by rduivenvoorde** [Sandro71/SensorThingsInspector_QGIS-plugin#17]
We are running the QGIS-flatpak  (https://qgis.org/resources/installation-guide/#flatpak) on a Redhat (stepstone) machine.

Apparently that one does not have QtWebKit:

```
ModuleNotFoundError: No module named 'PyQt5.QtWebKit' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duivenvr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/__init__.py", line 56, in classFactory
    from SensorThingsAPI.sensor_things_inspector import SensorThingsInspectorPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duivenvr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/sensor_things_inspector.py", line 33, in 
    from SensorThingsAPI.sensor_things_location_dlg import SensorThingsLocationDialog
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duivenvr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/sensor_things_location_dlg.py", line 39, in 
    from SensorThingsAPI.sensor_things_osservazioni_dlg import SensorThingsObservationDialog
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duivenvr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/sensor_things_osservazioni_dlg.py", line 41, in 
    from SensorThingsAPI.sensor_things_browser import SensorThingsWebView, SensorThingsRequestError
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duivenvr/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/sensor_things_browser.py", line 32, in 
    from qgis.PyQt.QtWebKit import QWebSettings
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/qgis/python/qgis/PyQt/QtWebKit.py", line 24, in 
    from PyQt5.QtWebKit import *
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'
```

From About, all version:

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.2-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.10</td></tr><tr><td>Python version</td><td>3.11.9</td></tr><tr><td>GDAL/OGR version</td><td>3.10.0</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.47.0</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.1.5</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>KDE Flatpak runtime</td></tr><tr><td colspan="2">&nbsp;</td></tr></table>

According to:  https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5 QtWebKit got deprecated upstream in Qt 5.5 and removed in 5.6...

The solutions there do not work (importing PyQt5.QtWebEngineWidgets stuff and naming it to WebKit names) failes later in code.

I'm not uptodate on the WebKit / WebEngine discussion, but apparently the latter is newer/safer?

Another reason to (maybe?) upgrade is a move to Qt6 of the plugin?

**Comment by rduivenvoorde** [comment]
@ghtmtt mmm, I see DataPlotly has the same issue?

**Comment by ghtmtt** [comment]
@rduivenvoorde mmm cannot experience the same problem with dataplotly, do you?

**Comment by rduivenvoorde** [comment]
> [@rduivenvoorde](https://github.com/rduivenvoorde) mmm cannot experience the same problem with dataplotly, do you?

Yes, even on my own laptop running Debian, and then running QGIS in flatpak:

```
ModuleNotFoundError: No module named 'PyQt5.QtWebKit' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 33, in classFactory
    from .data_plotly import DataPlotly
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 32, in 
    from DataPlotly.gui.dock import DataPlotlyDockManager
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/dock.py", line 19, in 
    from DataPlotly.gui.plot_settings_widget import DataPlotlyPanelWidget
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richard/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/plot_settings_widget.py", line 49, in 
    from qgis.PyQt.QtWebKit import QWebSettings
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/qgis/python/qgis/PyQt/QtWebKit.py", line 24, in 
    from PyQt5.QtWebKit import *
  File "/app/share/qgis/python/qgis/utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'
```

**Comment by ghtmtt** [comment]
seems fixed by updating `python3-pyqt5 `, see https://github.com/ghtmtt/DataPlotly/issues/363#issuecomment-2614115318 and thanks to @agiudiceandrea

**Comment by Sandro71** [comment]
Replaced WebKit with WebEngine widget.

**Comment by rduivenvoorde** [comment]
@Sandro71 what did you change? Because now the STAinspector v2.1.1 is working in my Flathub version

In contrast with DataPlotly v4.2.0 (@ghtmtt ) which still throws this same error, in the same QGIS ...

Should I close this issue here and move to DataPlotly?

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, STAinspector replaced the use of Qt WebKit with Qt WebEngine. DataPlotly still uses Qt WebKit. It looks like Qt WebKit is not available with QGIS from flatpak.
